services:
  project:
    build: .
    expose:
      - "80"
    environment:
      MYSQL_SERVER: db
      MYSQL_DATABASE: webappdb
      MYSQL_USER: webapp
      MYSQL_PASSWORD: 05N3tl9MZFAZ
      DB_USER: webapp
      DB_PASSWORD: 05N3tl9MZFAZ
      DATABASE_USER: webapp
      DATABASE_PASSWORD: 05N3tl9MZFAZ
    volumes:
      - ./public:/var/www/html/
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: change-me
      MYSQL_DATABASE: webappdb
      MYSQL_USER: webapp
      MYSQL_PASSWORD: 05N3tl9MZFAZ
    volumes:
      - dbvolume:/var/lib/mysql
      # Init-SQL
      - ./sql-scheme/webappdb-V6-1.sql:/docker-entrypoint-initdb.d/webappdb-init.sql:ro
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
    expose:
      - "80"
    restart: unless-stopped
    depends_on:
      - db

  caddy:
    image: caddy:2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - project
      - phpmyadmin

volumes:
  dbvolume: {}
  caddy_data: {}
  caddy_config: {}
